CREATE TABLE `magic`.`player` ( `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `magic`.`season` ( `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT , `name` VARCHAR(255) NULL DEFAULT NULL , `startDate` DATE NULL DEFAULT NULL , `endDate` DATE NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

CREATE TABLE `magic`.`game` ( `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT , `seasonId` BIGINT UNSIGNED NOT NULL , `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `game` ADD CONSTRAINT `game_to_season` FOREIGN KEY (`seasonId`) REFERENCES `season`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE `magic`.`concede` ( `gameId` BIGINT UNSIGNED NOT NULL , `playerId` BIGINT UNSIGNED NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `concede` ADD CONSTRAINT `concede_to_game` FOREIGN KEY (`gameId`) REFERENCES `game`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `concede` ADD CONSTRAINT `concede_to_player` FOREIGN KEY (`playerId`) REFERENCES `player`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `magic`.`concede` ADD UNIQUE `concedeGamePlayerIdx` (`gameId`, `playerId`);

CREATE TABLE `magic`.`points` ( `gameId` BIGINT UNSIGNED NOT NULL , `playerId` BIGINT UNSIGNED NOT NULL , `points` INT UNSIGNED NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `points` ADD CONSTRAINT `points_to_game` FOREIGN KEY (`gameId`) REFERENCES `game`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `points` ADD CONSTRAINT `points_to_player` FOREIGN KEY (`playerId`) REFERENCES `player`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `magic`.`points` ADD UNIQUE `pointsGamePlayerIdx` (`gameId`, `playerId`);

CREATE TABLE `magic`.`kills` ( `gameId` BIGINT UNSIGNED NOT NULL , `killerId` BIGINT UNSIGNED NULL DEFAULT NULL , `killedId` BIGINT UNSIGNED NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `kills` ADD CONSTRAINT `kills_to_game` FOREIGN KEY (`gameId`) REFERENCES `game`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `kills` ADD CONSTRAINT `kills_to_playerKiller` FOREIGN KEY (`killerId`) REFERENCES `player`(`id`) ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE `kills` ADD CONSTRAINT `kills_to_playerKilled` FOREIGN KEY (`killedId`) REFERENCES `player`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `magic`.`kills` ADD UNIQUE `killsGamePlayerIdx` (`gameId`, `killerId`, `killedId`);

CREATE TABLE `magic`.`quotes` ( `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT , `playerId` BIGINT UNSIGNED NULL DEFAULT NULL , `quote` VARCHAR(255) NOT NULL , `date` DATE NULL DEFAULT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `quotes` ADD CONSTRAINT `quotes_to_player` FOREIGN KEY (`playerId`) REFERENCES `player`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;